---
name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.13"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.6.5"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2
      with:
        version: ${{ inputs.uv-version }}

    - name: Install Python dependencies
      run: uv sync --frozen --no-dev --group test
      shell: bash
