---
name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.14"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.6.5"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244  # v7.1.4
      with:
        version: ${{ inputs.uv-version }}

    - name: Install Python dependencies
      run: uv sync --frozen --no-dev --group test
      shell: bash
